[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@gateway/=lib/on-chain-identity-gateway/ethereum/smart-contract"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config