[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@gateway/=lib/on-chain-identity-gateway/ethereum/smart-contract/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "solvprotocol/erc-3525/=lib/erc-3525/contracts/",
    "@solvprotocol/erc-3525/=lib/erc-3525/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config