[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@gateway/=lib/on-chain-identity-gateway/ethereum/smart-contract/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "solvprotocol/erc-3525/=lib/erc-3525/contracts/",
    "@solvprotocol/erc-3525/=lib/erc-3525/contracts/",
]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
local = "${LOCAL_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
mumbai = { key = "${POLYGONSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config